name: qinfer-examples
channels:
  - conda-forge
dependencies:
  - python=3.5
  - jupyter
  - matplotlib
  - qutip # Needed for tomography
  - configobj # Needed to read qutiprc files.
  - pandas # Needed for the simple estimation examples.
  # Not actually needed, but suppresses superfulous warnings
  # if we have parallelization support installed.
  - ipyparallel 
  - pip:
    - mpltools # Needed for Hinton diagrams.
    # Finally, install QInfer itself.
    - qinfer==1.0
